version: '3.8'
services:

  # Building and testing environment
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: ["/bin/bash"]